language: python
python:
  - "3.4"
before_install:
  # - npm install -g npm
  - nvm install node
  - npm --version
  # travis specific configuration to convince shell having a screen
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
install:
  - echo install
  - pwd
  - cd ./angular2-client
  - pwd
  - npm install
  - cd ..
  - pwd
  - pip install -r requirements.txt
before_script:
  - npm install -g firebase-tools
script:
  - echo script
  - pwd
  - cd ./angular2-client && npm run build
after_success:
  - echo after_success
  - pwd
  - firebase -V
  # we currently are in /angular-client dir
  - firebase deploy --token $FIREBASE_API_TOKEN
before_deploy:
  - echo before_deploy
  - cd ..
  - pwd
  - cd ./django-server
deploy:
  provider: heroku
  api_key: $HEROKU_API_KEY
  app: glacial-shore-18891